### ISSUE TITLE
Is Kibana correctly set up?

### ISSUE THREAD

**Issue by kamelzcs** [comperiosearch/vagrant-elk-box#8]
Ubuntu: 14.04
Vagrant: 1.6.5

```
==> default: Notice: /Stage[main]/Main/Exec[download_kibana]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Exec[start kibana]/returns: {"@timestamp":"2015-02-23T09:10:11.787Z","level":"error","node_env":"production","error":"Request error, retrying -- connect ECONNREFUSED"}
==> default: 
==> default: Notice: /Stage[main]/Main/Exec[start kibana]/returns: {"@timestamp":"2015-02-23T09:10:11.798Z","level":"warn","message":"Unable to revive connection: http://localhost:9200/","node_env":"production"}
==> default: Notice: /Stage[main]/Main/Exec[start kibana]/returns: {"@timestamp":"2015-02-23T09:10:11.799Z","level":"warn","message":"No living connections","node_env":"production"}
==> default: Notice: /Stage[main]/Main/Exec[start kibana]/returns: {"@timestamp":"2015-02-23T09:10:11.823Z","level":"fatal","message":"No Living connections","node_env":"production","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n  at sendReqWithConnection (/vagrant/kibana/kibana-4.0.0-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:174:15)\n  at next (/vagrant/kibana/kibana-4.0.0-linux-x64/src/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n  at process._tickCallback (node.js:442:13)\n"}}
==> default: Error: /vagrant/kibana/kibana-4.0.0-linux-x64/bin/kibana returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[start kibana]/returns: change from notrun to 0 failed: /vagrant/kibana/kibana-4.0.0-linux-x64/bin/kibana returned 1 instead of one of [0]

```

```
==> default: Notice: Finished catalog run in 527.58 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by babadofar** [comment]
Sorry about that, there was a missing dependency on the elastcsearch instance for the kibana start up.
Please do a new pull and try again. 
The import script fails quite often (due to 404 from the remote service), and kibana also quite often doesn't start up, so you might have to do it manually, as detailed in the readme

**Comment by kamelzcs** [comment]
I am using the master branch to parse the apache log.

I am wondering whether it is always necessary to create an index on
the elastic search and using mappings and store the data manually into the Elastisearch
like the import.py?

```
input {
  file {
    path => "/vagrant/project/logs/access.log"
    start_position => beginning
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "apache_access" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
      host => localhost
      }
  stdout { codec => rubydebug }
}

**Comment by kamelzcs** [comment]
It seems It has to declear the clustername manually!
```
output {
  elasticsearch {
      host => localhost
      cluster => vagrant_elasticsearch
      }
  stdout { codec => rubydebug }
}
```

**Comment by kamelzcs** [comment]
It would be helpful if the master branch could include a minimal configuration file like the one I mentioned above,  the current master branch requires elasticsearch client programming knowledge(import.py) to make it work, which is a big step for a beginner like me.

**Comment by babadofar** [comment]
I fixed the logstah config and added a sample log file. It is not necessary to use a python script to import, but there were some errors and misconfigurations in the config file. This should be fixed now.
I hope this makes you happy, if not, please file a new issue, as this one is spilling over:)
